swagger: "2.0"
info:
  title: "E-commerce API"
  description: "API for managing products, orders, and user authentication for an e-commerce platform."
  version: "1.0.0"
  contact:
    name: "TechAgent"
    email: "support@ecommerceapi.com"

paths:
  /api/v1/auth/register:
    post:
      summary: "Register a new user"
      description: "Creates a new user account with the provided credentials."
      parameters:
        - in: "body"
          name: "user"
          description: "User registration details"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "201":
          description: "User registered successfully"
        "400":
          description: "Invalid input"

  /api/v1/auth/login:
    post:
      summary: "User login"
      description: "Authenticates the user and returns a JWT for access."
      parameters:
        - in: "body"
          name: "credentials"
          description: "User login credentials"
          required: true
          schema:
            $ref: "#/definitions/Credentials"
      responses:
        "200":
          description: "User logged in successfully"
        "401":
          description: "Invalid credentials"

  /api/v1/products:
    post:
      summary: "Create a new product"
      description: "Adds a new product to the store. Only accessible by admin users."
      parameters:
        - in: "body"
          name: "product"
          description: "Product details"
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        "201":
          description: "Product created successfully"
        "401":
          description: "Unauthorized access"
        "500":
          description: "Server error"
      security:
        - BearerAuth: []

    get:
      summary: "Get all products"
      description: "Retrieves a list of all products available in the store."
      responses:
        "200":
          description: "List of products"

  /api/v1/products/{product_id}:
    put:
      summary: "Update a product"
      description: "Updates an existing product by ID. Only accessible by admin users."
      parameters:
        - in: "path"
          name: "product_id"
          required: true
          type: "string"
          description: "ID of the product to update"
        - in: "body"
          name: "product"
          description: "Updated product details"
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        "200":
          description: "Product updated successfully"
        "404":
          description: "Product not found"
        "401":
          description: "Unauthorized access"
      security:
        - BearerAuth: []

    delete:
      summary: "Delete a product"
      description: "Deletes an existing product by ID. Only accessible by admin users."
      parameters:
        - in: "path"
          name: "product_id"
          required: true
          type: "string"
          description: "ID of the product to delete"
      responses:
        "200":
          description: "Product deleted successfully"
        "404":
          description: "Product not found"
        "401":
          description: "Unauthorized access"
      security:
        - BearerAuth: []

  /api/v1/orders:
    post:
      summary: "Create a new order"
      description: "Creates a new order for the authenticated user."
      parameters:
        - in: "body"
          name: "order"
          description: "Order details"
          required: true
          schema:
            $ref: "#/definitions/Order"
      responses:
        "201":
          description: "Order created successfully"
        "400":
          description: "Invalid order data"
      security:
        - BearerAuth: []

  /api/v1/orders/{order_id}:
    get:
      summary: "View order details"
      description: "Retrieves details of a specific order for the authenticated user."
      parameters:
        - in: "path"
          name: "order_id"
          required: true
          type: "string"
          description: "ID of the order to retrieve"
      responses:
        "200":
          description: "Order details"
        "404":
          description: "Order not found"
        "401":
          description: "Unauthorized access"
      security:
        - BearerAuth: []

definitions:
  User:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
      email:
        type: "string"
    required:
      - "username"
      - "password"
      - "email"

  Credentials:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
    required:
      - "username"
      - "password"

  Product:
    type: "object"
    properties:
      name:
        type: "string"
      price:
        type: "number"
        format: "float"
      description:
        type: "string"
      stock:
        type: "integer"
    required:
      - "name"
      - "price"
      - "stock"

  Order:
    type: "object"
    properties:
      product_id:
        type: "string"
      quantity:
        type: "integer"
    required:
      - "product_id"
      - "quantity"

securityDefinitions:
  BearerAuth:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: "JWT Token for accessing secured endpoints"
 